[general]
version = "1.0"

# Maximum number of parallel workers for the segmentation stage.
n_workers = 5

# Segmentation
[segmentation]
  bulkfast5="./d"
  n_captures_per_file = 10
  voltage_threshold = 0.1
  signal_threshold_frac = 0.700000
  translocation_delay = 4
  end_tolerance = 4.4
  terminal_capture_only = false
  open_channel_prior_mean = 230
  open_channel_prior_stdv = 15
  [segmentation.capture_criteria]
    # Before even getting to the Filter step, we do some initial 'filtering' about
    # what can even potentially count as a capture.
    # You can think of the items in this section as the following: 
    # "A signal may or may not be a capture, but for it to even 
    # *possibly* be a capture, it must have the following characteristics:
    #
    [segmentation.capture_criteria.length]
      minimum = 100

[filters]
  # A unique name of your choice for this collection of filters, e.g. "NTER paper section 1"
  filter_set_name = "ProfessorJeffs_NTER_paper_draft_0"
  # Whether to filter based on the signal mean.
  [filters.mean]
    # Whether to filter based on the signal mean.
    # Minimum signal mean to pass. Defaults to -∞ if no value is provided.
    # minimum = 0
    # Maximum signal mean to pass. Defaults to +∞ if no value is provided.
    # maximum = 100
  [filters.min]
    # minimum = 0
    # maximum = 100

  [filters.length]
    minimum = 100
    #maximum = 100

[classifier]
  name = "foo"
  version = "v1.0"
  start = 100 # 100 in NTER paper
  end = 21000 # 21000 in NTER paper
  score_threshold = 0.8
