# Docker image workflow
name: DockerBuild

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v8
    # Runs a set of commands using the runners shell
    - name: Build docker image
      shell: bash
      run: |
           mkdir /tmp/artifacts
           dockerImagePath=`nix-build -A docker`
           cp $dockerImagePath /tmp/artifacts/poretitioner_docker.tar.gz

    # Uploads the docker image as a build artifact
    - name: Upload docker image
      uses: actions/upload-artifact@v1
      with:
        name: poretitioner_for_docker
        path: /tmp/artifacts/poretitioner_docker.tar.gz
