# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ jdunstan/docker-image ]
  pull_request:
    branches: [ jdunstan/docker-image ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v8
    # Runs a set of commands using the runners shell
    - name: Run build a docker 
      run: |
        dockerImagePath=$(nix-build -A docker)

    # Uploads the docker image as a build artifact
    - uses: actions/upload-artifact@v1
      with:
        name: poretitioner_for_docker
        path: $(dockerImagePath)
