
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v8

    # Build the app and its docker image, but don't upload the artifact.
    # We only upload the artifact on release branch builds, to conserve
    # storage space.
    - name: Build docker image
      shell: bash
      run: |
           nix-build -A docker
